repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10 # Match the version in pyproject.toml
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key

  # Using detect-secrets instead of gitleaks for secret detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        # Exclude documentation files with example credentials and lock files
        exclude: |
          (?x)(
            ^.secrets.baseline$|
            ^.pre-commit-config.yaml$|
            ^package-lock.json$|
            ^poetry.lock$|
            ^README.md$|
            ^PRD.md$
          )

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.34
    hooks:
      - id: checkov
        args:
          - --skip-framework=dockerfile,cloudformation,helm,kubernetes,kustomize,terraform
          - --framework=python
          - --soft-fail
          - --quiet
